---
title: "MS"
author: "Zita"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This will try to analyze MS data with R studio 

```{r setup, include = FALSE, echo=FALSE, warning=FALSE}
# Read libaries and functions --------------------------------------------------------------------

knitr::opts_chunk$set(echo = FALSE,  message=FALSE, warning = FALSE)

source('excel.R')
#source("functions.R")
#source('~/Documents/Code/R/theme.R')
```

```{r}
# Read data in from excel files =========

# Change to YOUR path to Dropbox
root_dir_ <- "/Users/zitaaretz/Dropbox/ms/"

# Leave this alone
data_dir_ <- paste0(root_dir_,"data/") 
results_dir_ <-  paste0(root_dir_,"results/")
analysis_dir_ <- paste0(root_dir_,"analysis/") 

fl <- list.files(data_dir_)
fl <- fl[str_detect(fl,".xlsx")]
fl <- paste0(data_dir_,fl)


r_sheet <-  function(files_path){
   files_path %>% excel_sheets() %>% purrr::set_names()  %>% map_df(read_excel, path = files_path, .id = "sheet")
}

df <-  fl %>%  map( ~ r_sheet(.)) %>%  bind_rows()

df %>%  distinct(sheet) %>% kable() %>% kable_styling(bootstrap_options = "striped", full_width = F)

#vvv(df)

df <- df %>% dplyr::select(sheet =1, time = 2,c(ends_with("M"))) %>% gather("mol","abs", c(ends_with("M")))  %>%  
  mutate(mol = as.double(str_replace(mol, "[:alpha:]","")))

df <- df %>%  mutate(polymer = str_extract(sheet, "^[:alnum:]+"), condition = str_extract(sheet, "(?<=pH\\d\\s)[:alnum:]+"), ph = str_extract(sheet, "(?<=pH)\\d"), treatment = str_extract(sheet, "\\w{1,2}(?=\\s([[:digit:]]|[[:punct:]]){1,4}mg)"), conc = str_extract(sheet, "([[:digit:]]|[[:punct:]]){1,4}(?=mg)"), run = str_extract(sheet, "(?<=\\()\\d"))
df$conc <- as.numeric(df$conc)
#%>%  select(spolymer, condition, mol, ph, treatment, run, time, abs)
df <- df %>% mutate(P = as.double(str_extract(polymer, "(?<=P)\\d+")), Q = as.double(str_extract(polymer, "(?<=Q)\\d+")))

#head(df)

write_csv(df, paste0(analysis_dir_, "aggregate_data.csv"))
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
