#setup file for pacakges needed
#get the excel files 
#go to specific sheet get values, remove duplicates, 
#order by log prob, get rid of modifications and .
install.packages("tidyverse")
install.packages("readxl")
install.packages("stringr")
install.packages("readxl")
# install.packages("devtools")
devtools::install_github("tidyverse/readxl")
#test to pull to githup 

suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(bookdown))
suppressPackageStartupMessages(library(bookdownplus))
suppressPackageStartupMessages(library(flatxml))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(pspline))
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(survminer))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(shinyjs))
suppressPackageStartupMessages(library(shinyFiles))
suppressPackageStartupMessages(library(bsplus))
suppressPackageStartupMessages(library(htmltools))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(tinytex))
suppressPackageStartupMessages(library(flexdashboard))
suppressPackageStartupMessages(library(flextable))
suppressPackageStartupMessages(library(ggfortify))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(methods))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(forcats))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(pspline))
suppressPackageStartupMessages(library(flextable))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(drc))